name: material_segmented_control
description: A segmented control widget like the one for iOS, but in Material design
version: 1.1.0
author: BENN<beagle-barks-contact@yahoo.com>
homepage: https://github.com/beagle-barks/material_segmented_control
documentation:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
